### ISSUE TITLE
`box-shadow` doesn't work without prefix vendors

### ISSUE THREAD

**Issue by CyrilKrylatov** [hteumeuleu/caniemail#286]
Hello there,

Thank you for this project, how life-saver as I'm developing some emails for the past few days.

Anyway, I have this issue. I have a link element and I want it to have a `box-shadow` like this:

```css
.button-link {
  display: inline-block;
  margin-bottom: 20px;
  padding: 12px 20px 11px;
  text-align: center;
  text-decoration: none;
  font-family: Arial,sans-serif;
  font-size: 14px;
  font-weight: 700;
  vertical-align: middle;
  color: #FFF;
  background: #000;
  box-shadow: 5px 5px 0 0 #FE6;
}
```

I tested it on macOS 12.5.1 + Mail Version 16.0 (3696.120.41.1.1) and the box-shadow went missing. It's missing too on Mail on iOS.

Then I added a `-webkit-box-shadow: 5px 5px 0 0 #FE6;` and the box-shadow was there.

So I think (this page)[https://www.caniemail.com/features/css-box-shadow/] should have a partial support for Apple Mail on macOS.

Cheers and thank you again!

✌️
