### ISSUE TITLE
.svg images

### ISSUE THREAD

**Issue by MMutch** [hteumeuleu/caniemail#32]
Add support for which clients can use .svg images

**Comment by fitztrev** [comment]
Adding to this, it would be good to mention support for other ways SVGs are used. Examples taken from [this css-tricks post](https://css-tricks.com/a-guide-on-svg-support-in-email/).

1. SVG as Image Tag

    ```html
    <img src="my-image.svg">
    ```

1. SVG as Inline HTML

    ```html
    <svg ...>
        <path d="..."/>
    </svg>
    ```

1. SVG as CSS background Image

    ```css
    .my-element {
        background-image: url("my-image.svg");
    }
    ```
